apel/grafana-dashboards

dashboards/grid.json

Add "None" option to Cloud and Grid Sites selections and add Cloud data to bottom charts and change them to be bar charts

Add "None" option and tidying bottom charts

---

dashboards/grid.json

Add link to IRIS website

---

dashboards/grid.json

Alter SQL queries to combine grid and cloud variables
Resolves #2

Combine grid and cloud features

---

dashboards/activity_view.json
dashboards/grid.json
dashboards/provider_view.json

Resolves #20.
Adds 2 new dashboards that can be reached through new navigation buttons 
and new drilldown on main graph. Simplifies main (home) dashboard with 
slightly expanded pie charts.

Split into 3 dashboards with new navigation links

---

iris-schema.sql

Add allocations table schema

---

dashboards/resource_manager.json

Resource manager view contains projection table and graph. This 
dashboard will not appear as a navigation button as it is not tagged 
under 'main'.

Add Resource manager view

---

dashboards/activity_view.json
dashboards/grid.json
dashboards/provider_view.json

Change hover tooltip mode to 'single'

---

dashboards/resource_manager.json

Fix 'Previous' column in projection table to handle new year

---

dashboards/provider_view.json

Panels to visualise SubmitHost job count for Sites
Resolves #52

Add SubmitHost panels

---

iris-initialisation.sql
iris-schema.sql

Add initialisation data for IrisVOs, Capacity, and Allocations

Add initialisation data 

---

README.md
provisioning/dashboards/iris.yml
provisioning/datasources/iris.yml

Add Provisioning files (with sensitive information removed) and add info on the directory structure to the README.

Provisioning & directory info

---

dashboards/grid.json

Fix relative links

---

dashboards/cloud/cloud.json

Tidy up main SCD cloud dashboard

---

dashboards/iris/resource_manager.json

Combines the two usage bar charts, removing the threshold and making y-axis dynamic

---

dashboards/iris/storage_accounting.json

A new dashboard for storage space accounting, an example of which can be found at http://172.16.113.197:3000/d/Vk27NpKGk/storage-accounting?orgId=1

Adds a new storage accounting dashboard

---

dashboards/iris/resource_manager.json
schemas/iris-schema.sql

Resolves #74 
Example of changes can be seen at http://172.16.114.44:3000/d/Tjeu74BMz/resource-manager?orgId=1

Adds cumulative usage and allocation table to resource manager dashboard

---

dashboards/iris/resource_manager.json

Resolves #75
Example of changes can be seen at http://172.16.114.44:3000/d/ecYaghfGk/resource-manager?orgId=1
This pull request builds on changes from issue 74

Adds current months allocation to projected usage table

---

dashboards/iris/activity_view.json

Adds table showing usage by month by VO by site to the activity view

---

dashboards/iris/resource_manager.json

Adds default zero projected usage when no data available for current month

---

dashboards/iris/activity_view.json

It looks like "VO" in the title should be "Site" instead: https://accounting.iris.ac.uk/d/TfxgjgJZk/activity-view?orgId=1

Change VO to Site in CPU time panel

---

dashboards/iris/activity_view.json
dashboards/iris/iris.json
dashboards/iris/provider_view.json
dashboards/iris/resource_manager.json
provisioning/datasources/iris.yml

closes #116 
Due to the way that our grafana setup works simply fixing the .yml file will automatically update the relevant dashboards in future.

Fix for cloud database error

---

dashboards/iris/iris.json

Resolves #121 
Changes can be seen at: http://172.16.112.119:3000/d/feTpkMumk-new/iris-accounting-dashboard?orgId=1
Dependant on PR #124

121 add allocation line

---

dashboards/cloud/cloud.json
dashboards/cloud/cloud_activity_view.json
dashboards/cloud/cloud_provider_view.json
dashboards/iris/activity_view.json
dashboards/iris/iris.json
dashboards/iris/provider_view.json
dashboards/iris/resource_manager.json
dashboards/iris/storage_accounting.json
dashboards/seadatacloud/container_accounting.json
dashboards/tier1/tier1.json
dashboards/tier1/tier1_activity_view.json
dashboards/tier1/tier1_provider_view.json
provisioning/dashboards/cloud.yml
provisioning/dashboards/iris.yml
provisioning/dashboards/seadatacloud.yml
provisioning/dashboards/tier1.yml

- Resolves #134
- Resolves #136 
- Disables updating of provisioned dashboards from within the UI
- ~~Corrects some SDC naming (not that that's used)~~

Mixed fixes

---

dashboards/iris/iris.json

- adds dropdown with options for both, none, just allocation and just capacity
resolves #151

[GT-142] Adds dropdown to select which line series appear

---

dashboards/iris/activity_view.json
dashboards/iris/iris.json
dashboards/iris/provider_view.json
dashboards/iris/resource_manager.json

Resolves #166 
Alters generalisation of days in month as 30.45 days to change based on month

Fix month length generalisation

---

dashboards/iris/accelerator_accounting.json

- Combines with changes to APEL in the add-accelerator-summaries-and-schemas or something or other branch
- Needs to be configured to run in the full dashboard inside Grafana's settings, but I can't add this as I don't know where the data will come from

Add a working accelerator dashboard

---

provisioning/dashboards/iris.yml
provisioning/datasources/iris.yml

Just a couple of tweaks to ready the dashboard side for deployment.

Tweak accelerator dash name and add db source

---

dashboards/iris/guide.json

No new panels, it's just that moving them around makes the diff noisy.

Rearrange some panels in guide and increase height

---

dashboards/intertwin/accelerator_accounting.json
provisioning/dashboards/intertwin.yml

Resolves GT-538
Copied accelerator_accounting.json file from dashboards/iris to the dashboards/intertwin directory
Changed iris_accelerator dataset name to intertwin_accelerator inside the intertwin/accelerator_accounting.json file as is just an internal reference
Added the new file path to the providers inside the intertwin.yml file

Copied accelerator accounting to InterTwin

---

provisioning/datasources/iris.yml
schemas/iris-schema.sql

For the migration to the centrally managed database, then schema names in this file need updating.

Update database name to match new db
